---
- name: install packages
  hosts: all
  become: true
  tasks:
   - name: install packages
     apt:
      name: "{{item}}"
      state: present
     with_items:
       - git
       - tree
       - maven
       - default-jdk
...
